### ISSUE TITLE
[FEATURE] Add Radiant Echo Item

### ISSUE THREAD

**Issue by agentschmitt** [AvyAddons/BetterBags_WarWithin#2]
## Feature Request
Can you add Radiant Echos to a category too?
https://www.wowhead.com/item=220520/radiant-echo

### Is your feature request related to a problem?
--

### What solution would you like?
I would add it to the Delves category, to have all sources for Delve Keys together.

### What alternatives have you considered?
--

### Do you have any additional context?
--

**Comment by lucasvienna** [comment]
Thanks for the suggestion, added in v1.4.1!
